package net.raescott.seleniumexample;

import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

import java.util.ArrayList;
import java.util.List;

@Controller
@RequestMapping("filtering-select")
public class FilteringSelectController {
	@RequestMapping(method = RequestMethod.GET)
	public String filteringSelectPage(ModelMap model) {
		model.addAttribute("message", "Page content");
		return "filtering-select";
	}

	@RequestMapping(value = "states", method = RequestMethod.GET)
	public @ResponseBody List<StateDto> stateService(ModelMap model) {
		List<StateDto> stateDtos = new ArrayList<StateDto>();
		stateDtos.add(new StateDto("Alabama", "AL"));
		stateDtos.add(new StateDto("Alaska", "AK"));
		stateDtos.add(new StateDto("American Samoa", "AS"));
		stateDtos.add(new StateDto("Arizona", "AZ"));
		stateDtos.add(new StateDto("Arkansas", "AR"));
		stateDtos.add(new StateDto("Armed Forces Europe", "AE"));
		stateDtos.add(new StateDto("Armed Forces Pacific", "AP"));
		stateDtos.add(new StateDto("Armed Forces the Americas", "AA"));
		stateDtos.add(new StateDto("California", "CA"));
		stateDtos.add(new StateDto("Colorado", "CO"));
		stateDtos.add(new StateDto("Connecticut", "CT"));
		stateDtos.add(new StateDto("Delaware", "DE"));
		stateDtos.add(new StateDto("District of Columbia", "DC"));
		stateDtos.add(new StateDto("Federated States of Micronesia", "FM"));
		stateDtos.add(new StateDto("Florida", "FL"));
		stateDtos.add(new StateDto("Georgia", "GA"));
		stateDtos.add(new StateDto("Guam", "GU"));
		stateDtos.add(new StateDto("Hawaii", "HI"));
		stateDtos.add(new StateDto("Idaho", "ID"));
		stateDtos.add(new StateDto("Illinois", "IL"));
		stateDtos.add(new StateDto("Indiana", "IN"));
		stateDtos.add(new StateDto("Iowa", "IA"));
		stateDtos.add(new StateDto("Kansas", "KS"));
		stateDtos.add(new StateDto("Kentucky", "KY"));
		stateDtos.add(new StateDto("Louisiana", "LA"));
		stateDtos.add(new StateDto("Maine", "ME"));
		stateDtos.add(new StateDto("Marshall Islands", "MH"));
		stateDtos.add(new StateDto("Maryland", "MD"));
		stateDtos.add(new StateDto("Massachusetts", "MA"));
		stateDtos.add(new StateDto("Michigan", "MI"));
		stateDtos.add(new StateDto("Minnesota", "MN"));
		stateDtos.add(new StateDto("Mississippi", "MS"));
		stateDtos.add(new StateDto("Missouri", "MO"));
		stateDtos.add(new StateDto("Montana", "MT"));
		stateDtos.add(new StateDto("Nebraska", "NE"));
		stateDtos.add(new StateDto("Nevada", "NV"));
		stateDtos.add(new StateDto("New Hampshire", "NH"));
		stateDtos.add(new StateDto("New Jersey", "NJ"));
		stateDtos.add(new StateDto("New Mexico", "NM"));
		stateDtos.add(new StateDto("New York", "NY"));
		stateDtos.add(new StateDto("North Carolina", "NC"));
		stateDtos.add(new StateDto("North Dakota", "ND"));
		stateDtos.add(new StateDto("Northern Mariana Islands", "MP"));
		stateDtos.add(new StateDto("Ohio", "OH"));
		stateDtos.add(new StateDto("Oklahoma", "OK"));
		stateDtos.add(new StateDto("Oregon", "OR"));
		stateDtos.add(new StateDto("Pennsylvania", "PA"));
		stateDtos.add(new StateDto("Puerto Rico", "PR"));
		stateDtos.add(new StateDto("Rhode Island", "RI"));
		stateDtos.add(new StateDto("South Carolina", "SC"));
		stateDtos.add(new StateDto("South Dakota", "SD"));
		stateDtos.add(new StateDto("Tennessee", "TN"));
		stateDtos.add(new StateDto("Texas", "TX"));
		stateDtos.add(new StateDto("Utah", "UT"));
		stateDtos.add(new StateDto("Vermont", "VT"));
		stateDtos.add(new StateDto("Virgin Islands, U.S.", "VI"));
		stateDtos.add(new StateDto("Virginia", "VA"));
		stateDtos.add(new StateDto("Washington", "WA"));
		stateDtos.add(new StateDto("West Virginia", "WV"));
		stateDtos.add(new StateDto("Wisconsin", "WI"));
		stateDtos.add(new StateDto("Wyoming", "WY"));

		return stateDtos;
	}
	@RequestMapping(value = "cities", method = RequestMethod.GET)
	public @ResponseBody List<CityDto> cityService(ModelMap model) {
		List<CityDto> cityDtos = new ArrayList<CityDto>();
		cityDtos.add(new CityDto("Alabama", "AL"));
		cityDtos.add(new CityDto("Albany", "NY"));
		cityDtos.add(new CityDto("Albuquerque", "NM"));
		cityDtos.add(new CityDto("Alexandria", "VA"));
		cityDtos.add(new CityDto("Amarillo", "TX"));
		cityDtos.add(new CityDto("Amherst", "MA"));
		cityDtos.add(new CityDto("Anaheim", "CA"));
		cityDtos.add(new CityDto("Anchorage", "AK"));
		cityDtos.add(new CityDto("Ann Arbor", "MI"));
		cityDtos.add(new CityDto("Annapolis", "MD"));
		cityDtos.add(new CityDto("Ashland", "OR"));
		cityDtos.add(new CityDto("Aspen", "CO"));
		cityDtos.add(new CityDto("Athens", "GA"));
		cityDtos.add(new CityDto("Atlanta", "GA"));
		cityDtos.add(new CityDto("Auburn", "AL"));
		cityDtos.add(new CityDto("Augusta", "GA"));
		cityDtos.add(new CityDto("Austin", "TX"));
		cityDtos.add(new CityDto("Baltimore", "MD"));
		cityDtos.add(new CityDto("Bangor", "ME"));
		cityDtos.add(new CityDto("Baton Rouge", "LA"));
		cityDtos.add(new CityDto("Bethlehem", "PA"));
		cityDtos.add(new CityDto("Beverly Hills", "CA"));
		cityDtos.add(new CityDto("Billings", "MT"));
		cityDtos.add(new CityDto("Biloxi", "MS"));
		cityDtos.add(new CityDto("Birmingham", "AL"));
		cityDtos.add(new CityDto("Bloomington", "IN"));
		cityDtos.add(new CityDto("Boca Raton", "FL"));
		cityDtos.add(new CityDto("Boise", "ID"));
		cityDtos.add(new CityDto("Boston", "MA"));
		cityDtos.add(new CityDto("Boulder", "CO"));
		cityDtos.add(new CityDto("Branson", "MO"));
		cityDtos.add(new CityDto("Buffalo", "NY"));
		cityDtos.add(new CityDto("Burbank", "CA"));
		cityDtos.add(new CityDto("Burlington", "VT"));
		cityDtos.add(new CityDto("Butte", "MT"));
		cityDtos.add(new CityDto("Cambridge", "MA"));
		cityDtos.add(new CityDto("Carmel", "CA"));
		cityDtos.add(new CityDto("Cedar Rapids", "IA"));
		cityDtos.add(new CityDto("Champaign-Urbana", "IL"));
		cityDtos.add(new CityDto("Chapel Hill", "NC"));
		cityDtos.add(new CityDto("Charleston", "SC"));
		cityDtos.add(new CityDto("Charleston", "WV"));
		cityDtos.add(new CityDto("Charlotte", "NC"));
		cityDtos.add(new CityDto("Chattanooga", "TN"));
		cityDtos.add(new CityDto("Chicago", "IL"));
		cityDtos.add(new CityDto("Cincinnati", "OH"));
		cityDtos.add(new CityDto("Clearwater Beach", "FL"));
		cityDtos.add(new CityDto("Cleveland", "OH"));
		cityDtos.add(new CityDto("Cody", "WY"));
		cityDtos.add(new CityDto("College Station", "TX"));
		cityDtos.add(new CityDto("Colorado Springs", "CO"));
		cityDtos.add(new CityDto("Columbia", "SC"));
		cityDtos.add(new CityDto("Columbus", "GA"));
		cityDtos.add(new CityDto("Columbus", "OH"));
		cityDtos.add(new CityDto("Concord", "NH"));
		cityDtos.add(new CityDto("Corpus Christi", "TX"));
		cityDtos.add(new CityDto("Dallas", "TX"));
		cityDtos.add(new CityDto("Dayton", "OH"));
		cityDtos.add(new CityDto("Daytona Beach", "FL"));
		cityDtos.add(new CityDto("Denver", "CO"));
		cityDtos.add(new CityDto("Des Moines", "IA"));
		cityDtos.add(new CityDto("Destin", "FL"));
		cityDtos.add(new CityDto("Detroit", "MI"));
		cityDtos.add(new CityDto("Dover", "DE"));
		cityDtos.add(new CityDto("Duluth", "MN"));
		cityDtos.add(new CityDto("Durham", "NC"));
		cityDtos.add(new CityDto("El Paso", "TX"));
		cityDtos.add(new CityDto("Erie", "PA"));
		cityDtos.add(new CityDto("Eugene", "OR"));
		cityDtos.add(new CityDto("Evansville", "IN"));
		cityDtos.add(new CityDto("Fairbanks", "AK"));
		cityDtos.add(new CityDto("Fargo", "ND"));
		cityDtos.add(new CityDto("Fayetteville", "NC"));
		cityDtos.add(new CityDto("Flagstaff", "AZ"));
		cityDtos.add(new CityDto("Fort Lauderdale", "FL"));
		cityDtos.add(new CityDto("Fort Wayne", "IN"));
		cityDtos.add(new CityDto("Fresno", "CA"));
		cityDtos.add(new CityDto("Ft. Worth", "TX"));
		cityDtos.add(new CityDto("Galveston", "TX"));
		cityDtos.add(new CityDto("Gatlinburg", "TN"));
		cityDtos.add(new CityDto("Grand Forks", "ND"));
		cityDtos.add(new CityDto("Greensboro", "NC"));
		cityDtos.add(new CityDto("Greenville", "SC"));
		cityDtos.add(new CityDto("Gulf Shores", "AL"));
		cityDtos.add(new CityDto("Hanover", "NH"));
		cityDtos.add(new CityDto("Harrisburg", "PA"));
		cityDtos.add(new CityDto("Hartford", "CT"));
		cityDtos.add(new CityDto("Hershey", "PA"));
		cityDtos.add(new CityDto("Hollywood", "CA"));
		cityDtos.add(new CityDto("Hot Springs", "AR"));
		cityDtos.add(new CityDto("Houston", "TX"));
		cityDtos.add(new CityDto("Huntsville", "AL"));
		cityDtos.add(new CityDto("Indianapolis", "IN"));
		cityDtos.add(new CityDto("Iowa City", "IA"));
		cityDtos.add(new CityDto("Ithaca", "NY"));
		cityDtos.add(new CityDto("Jackson", "MS"));
		cityDtos.add(new CityDto("Jacksonville", "FL"));
		cityDtos.add(new CityDto("Juneau", "AK"));
		cityDtos.add(new CityDto("Kalamazoo", "MI"));
		cityDtos.add(new CityDto("Kansas City", "KS"));
		cityDtos.add(new CityDto("Kansas City", "MO"));
		cityDtos.add(new CityDto("Kennebunkport", "ME"));
		cityDtos.add(new CityDto("Key West", "FL"));
		cityDtos.add(new CityDto("Knoxville", "TN"));
		cityDtos.add(new CityDto("Kodiak", "AK"));
		cityDtos.add(new CityDto("Laguna Beach", "CA"));
		cityDtos.add(new CityDto("Lansing", "MI"));
		cityDtos.add(new CityDto("Las Cruces", "NM"));
		cityDtos.add(new CityDto("Las Vegas", "NV"));
		cityDtos.add(new CityDto("Lexington", "KY"));
		cityDtos.add(new CityDto("Lincoln", "NE"));
		cityDtos.add(new CityDto("Little Rock", "AR"));
		cityDtos.add(new CityDto("Los Alamos", "NM"));
		cityDtos.add(new CityDto("Los Angeles", "CA"));
		cityDtos.add(new CityDto("Louisville", "KY"));
		cityDtos.add(new CityDto("Lynchburg", "VA"));
		cityDtos.add(new CityDto("Macon", "GA"));
		cityDtos.add(new CityDto("Madison", "WI"));
		cityDtos.add(new CityDto("Manchester", "NH"));
		cityDtos.add(new CityDto("Mankato", "MN"));
		cityDtos.add(new CityDto("Memphis", "TN"));
		cityDtos.add(new CityDto("Miami", "FL"));
		cityDtos.add(new CityDto("Milwaukee", "WI"));
		cityDtos.add(new CityDto("Minneapolis", "MN"));
		cityDtos.add(new CityDto("Mobile", "AL"));
		cityDtos.add(new CityDto("Moline", "IL"));
		cityDtos.add(new CityDto("Monterey", "CA"));
		cityDtos.add(new CityDto("Montgomery", "AL"));
		cityDtos.add(new CityDto("Montpelier", "VT"));
		cityDtos.add(new CityDto("Morgantown", "WV"));
		cityDtos.add(new CityDto("Myrtle Beach", "SC"));
		cityDtos.add(new CityDto("Naples", "FL"));
		cityDtos.add(new CityDto("Nashville", "TN"));
		cityDtos.add(new CityDto("New Haven", "CT"));
		cityDtos.add(new CityDto("New Orleans", "LA"));
		cityDtos.add(new CityDto("New York City", "NY"));
		cityDtos.add(new CityDto("Newark", "NJ"));
		cityDtos.add(new CityDto("Newport Beach", "CA"));
		cityDtos.add(new CityDto("Niagara Falls", "NY"));
		cityDtos.add(new CityDto("Norfolk", "VA"));
		cityDtos.add(new CityDto("Oakland", "CA"));
		cityDtos.add(new CityDto("Ogden", "UT"));
		cityDtos.add(new CityDto("Oklahoma City", "OK"));
		cityDtos.add(new CityDto("Olympia", "WA"));
		cityDtos.add(new CityDto("Omaha", "NE"));
		cityDtos.add(new CityDto("Orlando", "FL"));
		cityDtos.add(new CityDto("Palm Beach", "FL"));
		cityDtos.add(new CityDto("Palm Springs", "CA"));
		cityDtos.add(new CityDto("Palo Alto", "CA"));
		cityDtos.add(new CityDto("Panama City Beach", "FL"));
		cityDtos.add(new CityDto("Pasadena", "CA"));
		cityDtos.add(new CityDto("Pensacola", "FL"));
		cityDtos.add(new CityDto("Peoria", "IL"));
		cityDtos.add(new CityDto("Philadelphia", "PA"));
		cityDtos.add(new CityDto("Phoenix", "AZ"));
		cityDtos.add(new CityDto("Pierre", "SD"));
		cityDtos.add(new CityDto("Pigeon Forge", "TN"));
		cityDtos.add(new CityDto("Pittsburgh", "PA"));
		cityDtos.add(new CityDto("Pocatello", "ID"));
		cityDtos.add(new CityDto("Portland", "ME"));
		cityDtos.add(new CityDto("Portland", "OR"));
		cityDtos.add(new CityDto("Portsouth", "NH"));
		cityDtos.add(new CityDto("Princeton", "NJ"));
		cityDtos.add(new CityDto("Providence", "RI"));
		cityDtos.add(new CityDto("Raleigh", "NC"));
		cityDtos.add(new CityDto("Redondo Beach", "CA"));
		cityDtos.add(new CityDto("Reno", "NV"));
		cityDtos.add(new CityDto("Richmond", "VA"));
		cityDtos.add(new CityDto("Rochester", "MN"));
		cityDtos.add(new CityDto("Rochester", "NY"));
		cityDtos.add(new CityDto("Rockford", "IL"));
		cityDtos.add(new CityDto("Sacramento", "CA"));
		cityDtos.add(new CityDto("Salem", "OR"));
		cityDtos.add(new CityDto("Salt Lake City", "UT"));
		cityDtos.add(new CityDto("San Antonio", "TX"));
		cityDtos.add(new CityDto("San Diego", "CA"));
		cityDtos.add(new CityDto("San Francisco", "CA"));
		cityDtos.add(new CityDto("San Jose", "CA"));
		cityDtos.add(new CityDto("Santa Barbara", "CA"));
		cityDtos.add(new CityDto("Santa Cruz", "CA"));
		cityDtos.add(new CityDto("Santa Fe", "NM"));
		cityDtos.add(new CityDto("Santa Monica", "CA"));
		cityDtos.add(new CityDto("Sarasota", "FL"));
		cityDtos.add(new CityDto("Savannah", "GA"));
		cityDtos.add(new CityDto("Scottsdale", "AZ"));
		cityDtos.add(new CityDto("Scranton", "PA"));
		cityDtos.add(new CityDto("Seattle", "WA"));
		cityDtos.add(new CityDto("Shreveport", "LA"));
		cityDtos.add(new CityDto("Sioux Falls", "SD"));
		cityDtos.add(new CityDto("South Bend", "IN"));
		cityDtos.add(new CityDto("Spokane", "WA"));
		cityDtos.add(new CityDto("Springfield", "MA"));
		cityDtos.add(new CityDto("St. Louis", "MO"));
		cityDtos.add(new CityDto("St. Paul", "MN"));
		cityDtos.add(new CityDto("St. Petersburg", "FL"));
		cityDtos.add(new CityDto("StateDto College", "PA"));
		cityDtos.add(new CityDto("Sun Valley", "ID"));
		cityDtos.add(new CityDto("Syracuse", "NY"));
		cityDtos.add(new CityDto("Tacoma", "WA"));
		cityDtos.add(new CityDto("Tallahassee", "FL"));
		cityDtos.add(new CityDto("Tampa", "FL"));
		cityDtos.add(new CityDto("Telluride", "CO"));
		cityDtos.add(new CityDto("Tempe", "AZ"));
		cityDtos.add(new CityDto("Terre Haute", "IN"));
		cityDtos.add(new CityDto("Toledo", "OH"));
		cityDtos.add(new CityDto("Topeka", "KS"));
		cityDtos.add(new CityDto("Traverse City", "MI"));
		cityDtos.add(new CityDto("Trenton", "NJ"));
		cityDtos.add(new CityDto("Tucson", "AZ"));
		cityDtos.add(new CityDto("Tulsa", "OK"));
		cityDtos.add(new CityDto("Vail", "CO"));
		cityDtos.add(new CityDto("Virginia Beach", "VA"));
		cityDtos.add(new CityDto("Washington", "DC"));
		cityDtos.add(new CityDto("Wheeling", "WV"));
		cityDtos.add(new CityDto("Wichita", "KS"));
		cityDtos.add(new CityDto("Williamsburg", "VA"));
		cityDtos.add(new CityDto("Wilmington", "DE"));
		cityDtos.add(new CityDto("Winston-Salem", "NC"));
		cityDtos.add(new CityDto("Worcester", "MA"));
		cityDtos.add(new CityDto("Yellowstone", "WY"));
		cityDtos.add(new CityDto("York", "PA"));

		return cityDtos;
	}
}
